# Generated by Django 3.2.3 on 2021-06-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewcalendar', '0005_alter_user_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slots',
            field=models.JSONField(blank=True, default={'slots': []}),
        ),
    ]
