# Generated by Django 3.2.3 on 2021-06-01 16:28

from django.db import migrations, models
import interviewcalendar.models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewcalendar', '0006_alter_user_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slots',
            field=models.JSONField(default=interviewcalendar.models.get_default_dict),
        ),
    ]
